### ISSUE TITLE
Evictor.Builder expected in the config object?

### ISSUE THREAD

**Issue by naditina** [liveontologies/elk-reasoner#52]
Hi,

I'm trying out a 2 weeks old snapshot version of ELK. When I try to load a reasoner with any ontology, I get a null pointer because an Evictor.Builder object is expected in the config object.

at org.semanticweb.elk.reasoner.tracing.TraceState.<init>(TraceState.java:184)

Setting a String value in the ReasonerConfiguration object does not help because the value is expected to be of type Evictor.Builder. 

How can I resolve the problem?

Thanks
Nadeschda

**Comment by ykazakov** [comment]
Can you provide a small example to reproduce the problrm?

13 мая 2018 г. 14:34 пользователь "naditina" <notifications@github.com>
написал:

Hi,

I'm trying out a 2 weeks old snapshot version of ELK. When I try to load a
reasoner with any ontology, I get a null pointer because an Evictor.Builder
object is expected in the config object.

at org.semanticweb.elk.reasoner.tracing.TraceState.(TraceState.java:184)

Setting a String value in the ReasonerConfiguration object does not help
because the value is expected to be of type Evictor.Builder.

How can I resolve the problem?

Thanks
Nadeschda

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/liveontologies/elk-reasoner/issues/52>, or mute the
thread

**Comment by naditina** [comment]
Hi,

here is my code to load ELK:

final ReasonerConfiguration innerConfig = new ReasonerConfiguration();
innerConfig.setParameter(ReasonerConfiguration.INCREMENTAL_MODE_ALLOWED,"true");
//innerConfig.setParameter(ReasonerConfiguration.TRACING_EVICTOR," ");
innerConfig.setParameter(ReasonerConfiguration.NUM_OF_WORKING_THREADS,
"16");
final OWLReasonerConfiguration config = new ElkReasonerConfiguration(new
SimpleConfiguration(),
                    innerConfig);
new ElkReasonerFactory().createReasoner(o, config);


snapshot was taken on the 15th of April.

Stacktrace:

Exception in thread "main" java.lang.NullPointerException
    at
org.semanticweb.elk.reasoner.tracing.TraceState.<init>(TraceState.java:184)
    at
org.semanticweb.elk.reasoner.stages.AbstractReasonerState.<init>(AbstractReasonerState.java:219)
    at org.semanticweb.elk.reasoner.Reasoner.<init>(Reasoner.java:109)
    at
org.semanticweb.elk.reasoner.ReasonerFactory.createReasoner(ReasonerFactory.java:107)
    at
org.semanticweb.elk.reasoner.ReasonerFactory.createReasoner(ReasonerFactory.java:99)
    at
org.semanticweb.elk.reasoner.ReasonerFactory.createReasoner(ReasonerFactory.java:92)
    at org.semanticweb.elk.owlapi.ElkReasoner.<init>(ElkReasoner.java:197)
    at
org.semanticweb.elk.owlapi.ElkReasonerFactory.createElkReasoner(ElkReasonerFactory.java:102)
    at
org.semanticweb.elk.owlapi.ElkReasonerFactory.createReasoner(ElkReasonerFactory.java:82)
    at
protegeviewminimiser.CyclicViewSimplifier.getReasoner(CyclicViewSimplifier.java:366)
...

Nadeschda

**Comment by ykazakov** [comment]
What happens if you fo not change any configurations?

вс, 13 мая 2018, 14:43 naditina <notifications@github.com>:

> Hi,
>
> here is my code to load ELK:
>
> final ReasonerConfiguration innerConfig = new ReasonerConfiguration();
>
> innerConfig.setParameter(ReasonerConfiguration.INCREMENTAL_MODE_ALLOWED,"true");
> //innerConfig.setParameter(ReasonerConfiguration.TRACING_EVICTOR," ");
> innerConfig.setParameter(ReasonerConfiguration.NUM_OF_WORKING_THREADS,
> "16");
> final OWLReasonerConfiguration config = new ElkReasonerConfiguration(new
> SimpleConfiguration(),
> innerConfig);
> new ElkReasonerFactory().createReasoner(o, config);
>
>
> snapshot was taken on the 15th of April.
>
> Stacktrace:
>
> Exception in thread "main" java.lang.NullPointerException
> at
> org.semanticweb.elk.reasoner.tracing.TraceState.<init>(TraceState.java:184)
> at
>
> org.semanticweb.elk.reasoner.stages.AbstractReasonerState.<init>(AbstractReasonerState.java:219)
> at org.semanticweb.elk.reasoner.Reasoner.<init>(Reasoner.java:109)
> at
>
> org.semanticweb.elk.reasoner.ReasonerFactory.createReasoner(ReasonerFactory.java:107)
> at
>
> org.semanticweb.elk.reasoner.ReasonerFactory.createReasoner(ReasonerFactory.java:99)
> at
>
> org.semanticweb.elk.reasoner.ReasonerFactory.createReasoner(ReasonerFactory.java:92)
> at org.semanticweb.elk.owlapi.ElkReasoner.<init>(ElkReasoner.java:197)
> at
>
> org.semanticweb.elk.owlapi.ElkReasonerFactory.createElkReasoner(ElkReasonerFactory.java:102)
> at
>
> org.semanticweb.elk.owlapi.ElkReasonerFactory.createReasoner(ElkReasonerFactory.java:82)
> at
>
> protegeviewminimiser.CyclicViewSimplifier.getReasoner(CyclicViewSimplifier.java:366)
> ...
>
> Nadeschda
>

**Comment by naditina** [comment]
new ElkReasonerConfiguration(new SimpleConfiguration()); works fine. As
soon as I pass it a ReasonerConfiguration object, it stops working.

**Comment by ykazakov** [comment]
Is there any particular problem you whant to solve? Why do you need a
custom configurations?
I think most of ELK settings can be changed using java properties. Ser here
for example:

https://github.com/liveontologies/elk-reasoner/blob/master/elk-cli/src/test/resources/elk.properties

вс, 13 мая 2018, 15:13 naditina <notifications@github.com>:

> new ElkReasonerConfiguration(new SimpleConfiguration()); works fine. As
> soon as I pass it a ReasonerConfiguration object, it stops working.
>
>

**Comment by naditina** [comment]
I'm using in via the OWL API in a java program. If I put a properties file
in the project folder in my workspace, will ELK load it?

**Comment by ykazakov** [comment]
вс, 13 мая 2018, 15:36 naditina <notifications@github.com>:

> I'm using in via the OWL API in a java program. If I put a properties file
> in the project folder in my workspace, will ELK load it?
>

Yes provided it is on the classpath. You can also supply the values using
java command-line options -Dproperty=value.
