### ISSUE TITLE
ELK 0.5-SNAPSHOT throws error when initiated with Protege 5.5

### ISSUE THREAD

**Issue by rsgoncalves** [liveontologies/elk-reasoner#55]
After building ELK and dropping elk-protege-0.5.0-SNAPSHOT to the plugins folder of Protege 5.5 (beta 2), the Protege log shows the following error:

```
2018-08-08 11:41:36.952 [FelixStartLevel] ERROR FrameworkSlf4jLogger    Error starting file:/Applications/Protégé.app/Contents/Java/plugins/elk-protege-0.5.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Unresolved constraint in bundle org.semanticweb.elk [26]: Unable to resolve 26.0: missing requirement [26.0] osgi.wiring.package; (&(osgi.wiring.package=org.liveontologies.puli)(version>=0.1.0)(!(version>=1.0.0)))
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2045) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304) [org.apache.felix.main.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

**Comment by matentzn** [comment]
Did you drop puli.jar in there as well?

**Comment by matentzn** [comment]
(Its in the download folder of the ELK plugin)

**Comment by rsgoncalves** [comment]
No I didn't -- Adding puli.jar fixes the problem. So ELK v0.5 does seem to work fine for me on Protege 5.5 b2. Do you have error reports from previous attempts @matentzn?

**Comment by rsgoncalves** [comment]
Good to hear!
