### ISSUE TITLE
 java.lang.NoSuchMethodError: org.semanticweb.owlapi.model.OWLObjectSomeValuesFrom.getFiller()L

### ISSUE THREAD

**Issue by kahunmedicaltal** [liveontologies/elk-reasoner#65]
I am trying to run the below small test and getting an exception. I am using:

   implementation group: 'net.sourceforge.owlapi', name: 'owlapi-distribution', version: '5.1.17'
   implementation group: 'org.semanticweb.elk', name: 'elk-owlapi', version: '0.4.3'

I would appreciate any help.

Thank you

P.S. I suppose the problem is on my side. Hope this is the correct place to raise such an issue. If not, please let me know

======================== Terst.java =======================
package elktest;

import org.semanticweb.elk.owlapi.ElkReasonerFactory;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLObjectProperty;
import org.semanticweb.owlapi.model.OWLObjectSomeValuesFrom;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyManager;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;
import org.semanticweb.owlapi.model.OWLSubClassOfAxiom;
import org.semanticweb.owlapi.reasoner.InferenceType;
import org.semanticweb.owlapi.reasoner.OWLReasoner;
import org.semanticweb.owlapi.reasoner.OWLReasonerFactory;

public class Test {

	public static void main(String[] args) throws OWLOntologyStorageException,
			OWLOntologyCreationException {
		f();
	}

	public static void f() throws OWLOntologyStorageException, OWLOntologyCreationException {

		OWLOntologyManager manager = OWLManager.createOWLOntologyManager();

		OWLOntology ont = manager.createOntology();

		OWLReasonerFactory reasonerFactory = new ElkReasonerFactory();
		OWLReasoner reasoner = reasonerFactory.createReasoner(ont);

		OWLDataFactory factory = manager.getOWLDataFactory();
		OWLClass p = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/galen_p"));
		OWLClass q = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/galen_q"));
		OWLObjectProperty r = factory.getOWLObjectProperty(IRI.create("http://example.com/hasPart"));
		OWLObjectSomeValuesFrom xq = factory.getOWLObjectSomeValuesFrom(r, q);
		OWLSubClassOfAxiom a = factory.getOWLSubClassOfAxiom(p, xq);

		manager.addAxiom(ont, a);

		reasoner.flush();
		reasoner.precomputeInferences(InferenceType.CLASS_HIERARCHY);		
	}

}
======================== Exception =======================

Exception in thread "main" java.lang.NoSuchMethodError: org.semanticweb.owlapi.model.OWLObjectSomeValuesFrom.getFiller()Lorg/semanticweb/owlapi/model/OWLPropertyRange;
	at org.semanticweb.elk.owlapi.wrapper.ElkObjectSomeValuesFromWrap.getFiller(ElkObjectSomeValuesFromWrap.java:55)
	at org.semanticweb.elk.owlapi.wrapper.ElkObjectSomeValuesFromWrap.getFiller(ElkObjectSomeValuesFromWrap.java:40)
	at org.semanticweb.elk.reasoner.indexing.hierarchy.IndexObjectConverter.visit(IndexObjectConverter.java:195)
	at org.semanticweb.elk.reasoner.indexing.hierarchy.IndexObjectConverter.visit(IndexObjectConverter.java:59)
	at org.semanticweb.elk.owlapi.wrapper.ElkObjectSomeValuesFromWrap.accept(ElkObjectSomeValuesFromWrap.java:60)
	at org.semanticweb.elk.reasoner.indexing.hierarchy.MainAxiomIndexerVisitor.indexSubClassOfAxiom(MainAxiomIndexerVisitor.java:146)
	at org.semanticweb.elk.reasoner.indexing.hierarchy.AbstractElkAxiomIndexerVisitor.visit(AbstractElkAxiomIndexerVisitor.java:183)
	at org.semanticweb.elk.reasoner.indexing.hierarchy.AbstractElkAxiomIndexerVisitor.visit(AbstractElkAxiomIndexerVisitor.java:63)
	at org.semanticweb.elk.owlapi.wrapper.ElkSubClassOfAxiomWrap.accept(ElkSubClassOfAxiomWrap.java:58)
	at org.semanticweb.elk.owlapi.wrapper.ElkClassAxiomWrap.accept(ElkClassAxiomWrap.java:51)
	at org.semanticweb.elk.reasoner.indexing.hierarchy.DelegatingElkAxiomVisitor.visit(DelegatingElkAxiomVisitor.java:108)
	at org.semanticweb.elk.reasoner.indexing.hierarchy.DelegatingElkAxiomVisitor.visit(DelegatingElkAxiomVisitor.java:74)
	at org.semanticweb.elk.owlapi.wrapper.ElkSubClassOfAxiomWrap.accept(ElkSubClassOfAxiomWrap.java:58)
	at org.semanticweb.elk.owlapi.wrapper.ElkClassAxiomWrap.accept(ElkClassAxiomWrap.java:51)
	at org.semanticweb.elk.reasoner.indexing.hierarchy.ChangeIndexingProcessor.visit(ChangeIndexingProcessor.java:57)
	at org.semanticweb.elk.owlapi.OwlOntologyChangeProcessorVisitor.visit(OwlOntologyChangeProcessorVisitor.java:78)
	at org.semanticweb.elk.owlapi.OwlOntologyChangeProcessorVisitor.visit(OwlOntologyChangeProcessorVisitor.java:39)
	at org.semanticweb.owlapi.model.AddAxiom.accept(AddAxiom.java:68)
	at org.semanticweb.elk.owlapi.OwlChangesLoader.load(OwlChangesLoader.java:90)
	at org.semanticweb.elk.reasoner.stages.AxiomLoadingStage.executeStage(AxiomLoadingStage.java:121)
	at org.semanticweb.elk.reasoner.stages.AbstractReasonerStage.execute(AbstractReasonerStage.java:165)
	at org.semanticweb.elk.reasoner.stages.AxiomLoadingStage.execute(AxiomLoadingStage.java:45)
	at org.semanticweb.elk.reasoner.stages.LoggingStageExecutor.execute(LoggingStageExecutor.java:53)
	at org.semanticweb.elk.reasoner.stages.AbstractStageExecutor.complete(AbstractStageExecutor.java:55)
	at org.semanticweb.elk.reasoner.stages.AbstractReasonerState.complete(AbstractReasonerState.java:145)
	at org.semanticweb.elk.reasoner.stages.AbstractReasonerState.loadAxioms(AbstractReasonerState.java:306)
	at org.semanticweb.elk.reasoner.stages.AbstractReasonerState.isInconsistent(AbstractReasonerState.java:284)
	at org.semanticweb.elk.reasoner.stages.AbstractReasonerState.getTaxonomy(AbstractReasonerState.java:324)
	at org.semanticweb.elk.owlapi.ElkReasoner.precomputeInferences(ElkReasoner.java:942)
	at elktest.Test.f(Test.java:47)
	at elktest.Test.main(Test.java:24)

**Comment by ykazakov** [comment]
ELK 0.4.3 is not compatible with OWL API 5.x.x. See #48
